# Generated by Django 4.2.30 on 2026-05-05 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_delete_projectmeetingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_sessions', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrum_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScrumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=32)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('open_text', 'Open text'), ('audio', 'Audio'), ('system', 'System')], default='text', max_length=32)),
                ('text_content', models.TextField(blank=True)),
                ('structured_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='scrum.scrumsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMeetingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_days', models.JSONField(blank=True, default=list)),
                ('meeting_time', models.TimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('google_meet_link', models.URLField(max_length=500)),
                ('weekly_goals', models.TextField(blank=True)),
                ('monthly_goals', models.TextField(blank=True)),
                ('alert_minutes_before', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_settings', to='projects.project')),
            ],
            options={
                'db_table': 'projects_projectmeetingsettings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScrumToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('safe_input_summary', models.JSONField(blank=True, default=dict)),
                ('safe_result_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=32)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='scrum.scrummessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='scrum.scrumsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['session', 'tool_name'], name='scrum_tool_session_name_idx'), models.Index(fields=['session', 'status'], name='scrum_tool_session_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='scrumsession',
            index=models.Index(fields=['user', 'status'], name='scrum_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scrumsession',
            index=models.Index(fields=['project', 'status'], name='scrum_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scrummessage',
            index=models.Index(fields=['session', 'created_at'], name='scrum_msg_session_date_idx'),
        ),
        migrations.AddIndex(
            model_name='scrummessage',
            index=models.Index(fields=['session', 'role'], name='scrum_msg_session_role_idx'),
        ),
    ]
