# Generated by Django 4.2.30 on 2026-05-06 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0002_board_card_label_comment_column_cardlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_boards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
