# Generated by Django 4.2.30 on 2026-05-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_board_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
        migrations.AddField(
            model_name='card',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='card',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('is_standalone', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('linked_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='scrum.card')),
            ],
            options={
                'db_table': 'calendar_event',
            },
        ),
    ]
