# Generated by Django 4.2.30 on 2026-05-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_delete_projectmeetingsettings'),
        ('scrum', '0004_remove_card_due_date_card_all_day_card_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_number', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=16)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('assignees', models.JSONField(blank=True, default=list)),
                ('github_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_issues', to='projects.project')),
            ],
            options={
                'ordering': ['-github_number'],
                'indexes': [models.Index(fields=['project', 'state'], name='scrum_githu_project_7f0941_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='githubissue',
            constraint=models.UniqueConstraint(fields=('project', 'github_number'), name='unique_project_github_issue'),
        ),
    ]
