# Generated by Django 4.2.30 on 2026-05-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectauditlog_event_type'),
        ('scrum', '0005_githubissue_githubissue_unique_project_github_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_boards', to='projects.project'),
        ),
    ]
