export const mockUser = {
  id: 7,
  github_id: '74211',
  username: 'khaki-scout',
  name: 'Avery Khaki',
  email: 'avery.khaki@example.com',
  avatar_url: '',
  created_at: '2026-01-11T08:00:00Z',
  updated_at: '2026-04-15T08:00:00Z',
};

export const mockUserDescription = {
  id: 4,
  user_id: 7,
  username: 'khaki-scout',
  name: 'Avery Khaki',
  email: 'avery.khaki@example.com',
  primary_role: 'Frontend Engineer',
  experience_level: 'Intermediate',
  summary: 'Focuses on UI polish, collaboration, and steady delivery.',
  skills: [
    { name: 'React', level: 4 },
    { name: 'UX copy', level: 3 },
  ],
  preferred_tasks: ['UI refactors', 'Workflow alignment'],
  avoided_tasks: ['Low context hotfixes'],
  availability_notes: 'Best in the mornings, Pacific time.',
  agent_notes: '',
  created_at: '2026-01-11T08:00:00Z',
  updated_at: '2026-04-15T08:00:00Z',
};

export const mockProjects = [
  {
    id: 12,
    creator_id: 7,
    creator_username: 'khaki-scout',
    github_repo_id: 90210,
    github_full_name: 'khaki-labs/guardrail',
    github_html_url: 'https://github.com/khaki-labs/guardrail',
    github_clone_url: 'https://github.com/khaki-labs/guardrail.git',
    github_default_branch: 'main',
    github_visibility: 'private',
    github_primary_language: 'Python',
    github_languages: { Python: 87, HTML: 13 },
    github_description: 'Security automation workflows.',
    github_is_private: true,
    overview: 'A project to track vulnerabilities and align remediation.',
    goals: 'Reduce audit drift across sprints.',
    tech_stack: ['Django', 'React', 'Postgres'],
    business_context: 'Internal tooling for compliance and audits.',
    agent_notes: 'Prioritize project meeting cadence.',
    created_at: '2026-04-10T08:00:00Z',
    updated_at: '2026-04-20T08:00:00Z',
  },
  {
    id: 14,
    creator_id: 7,
    creator_username: 'khaki-scout',
    github_repo_id: 80331,
    github_full_name: 'khaki-labs/pinecone',
    github_html_url: 'https://github.com/khaki-labs/pinecone',
    github_clone_url: 'https://github.com/khaki-labs/pinecone.git',
    github_default_branch: 'main',
    github_visibility: 'public',
    github_primary_language: 'TypeScript',
    github_languages: { TypeScript: 76, CSS: 24 },
    github_description: 'Agent dashboard for compliance reviews.',
    github_is_private: false,
    overview: 'Comms for senior dev agent sessions.',
    goals: 'Improve team observability and reporting.',
    tech_stack: ['TypeScript', 'Vite'],
    business_context: 'Companion UI for QA and agent outputs.',
    agent_notes: 'Keep cues short and actionable.',
    created_at: '2026-03-02T08:00:00Z',
    updated_at: '2026-04-22T08:00:00Z',
  },
];

export const mockGithubRepositories = [
  {
    github_repo_id: 441921,
    name: 'guardrail',
    full_name: 'khaki-labs/guardrail',
    owner_login: 'khaki-labs',
    owner_avatar_url: '',
    html_url: 'https://github.com/khaki-labs/guardrail',
    clone_url: 'https://github.com/khaki-labs/guardrail.git',
    default_branch: 'main',
    visibility: 'private',
    primary_language: 'Python',
    description: 'Security automation workflows.',
    is_private: true,
    is_fork: false,
    is_archived: false,
    updated_at: '2026-04-21T08:00:00Z',
  },
  {
    github_repo_id: 441922,
    name: 'pinecone',
    full_name: 'khaki-labs/pinecone',
    owner_login: 'khaki-labs',
    owner_avatar_url: '',
    html_url: 'https://github.com/khaki-labs/pinecone',
    clone_url: 'https://github.com/khaki-labs/pinecone.git',
    default_branch: 'main',
    visibility: 'public',
    primary_language: 'TypeScript',
    description: 'Agent dashboard for compliance reviews.',
    is_private: false,
    is_fork: false,
    is_archived: false,
    updated_at: '2026-04-22T08:00:00Z',
  },
];

export const mockMembers = [
  {
    id: 5,
    project_id: 12,
    user_id: 7,
    username: 'khaki-scout',
    name: 'Avery Khaki',
    avatar_url: '',
    invited_by_id: 7,
    display_role: 'Project Lead',
    roles: ['owner', 'security'],
    created_at: '2026-04-10T08:00:00Z',
    updated_at: '2026-04-10T08:00:00Z',
  },
  {
    id: 6,
    project_id: 12,
    user_id: 9,
    username: 'sage-crew',
    name: 'Jordan Sage',
    avatar_url: '',
    invited_by_id: 7,
    display_role: 'Backend',
    roles: ['api', 'infra'],
    created_at: '2026-04-12T08:00:00Z',
    updated_at: '2026-04-12T08:00:00Z',
  },
];

export const mockTasks = [
  {
    id: 21,
    project_id: 12,
    assigned_to_id: 6,
    assigned_to_user_id: 9,
    assigned_to_username: 'sage-crew',
    assigned_to_name: 'Jordan Sage',
    related_finding_id: null,
    title: 'Harden webhook validation',
    description: 'Verify webhook signatures and rotate secrets.',
    category: 'security',
    priority: 'high',
    status: 'in_progress',
    created_by_agent: 'sr_dev',
    reasoning: 'Most visible risk in audit logs.',
    confidence_score: 82,
    confidence_reason: 'Webhook pattern is shared across services.',
    evidence: 'Audit log entries show missing signature check.',
    due_date: '2026-05-15',
    created_at: '2026-04-20T08:00:00Z',
    updated_at: '2026-04-22T08:00:00Z',
  },
  {
    id: 22,
    project_id: 12,
    assigned_to_id: 5,
    assigned_to_user_id: 7,
    assigned_to_username: 'khaki-scout',
    assigned_to_name: 'Avery Khaki',
    related_finding_id: null,
    title: 'Add meeting cadence banner',
    description: 'Surface next meeting time on project dashboard.',
    category: 'product',
    priority: 'medium',
    status: 'todo',
    created_by_agent: 'sr_dev',
    reasoning: 'Keeps team aligned on check-ins.',
    confidence_score: 74,
    confidence_reason: 'UX tested with PM flow.',
    evidence: 'Stakeholder feedback summary.',
    due_date: '2026-05-18',
    created_at: '2026-04-21T08:00:00Z',
    updated_at: '2026-04-21T08:00:00Z',
  },
];

export const mockVulnerabilities = [
  {
    id: 33,
    project_id: 12,
    agent_name: 'sr_dev',
    source: 'repository_scan',
    title: 'Missing auth guard on admin endpoint',
    summary: 'Admin endpoint allows unauthenticated access.',
    severity: 'high',
    status: 'open',
    category: 'auth',
    affected_area: 'API',
    affected_path: '/admin/reports/',
    evidence: 'Endpoint responds without auth header.',
    recommendation: 'Add IsAuthenticated + permission checks.',
    confidence_score: 88,
    confidence_reason: 'Verified via request log.',
    created_at: '2026-04-22T08:00:00Z',
    updated_at: '2026-04-22T08:00:00Z',
  },
  {
    id: 34,
    project_id: 12,
    agent_name: 'sr_dev',
    source: 'lint_check',
    title: 'Sensitive token logged in debug',
    summary: 'Debug logs capture refresh tokens.',
    severity: 'medium',
    status: 'open',
    category: 'logging',
    affected_area: 'Auth',
    affected_path: '/auth/refresh/',
    evidence: 'Structured log includes token payload.',
    recommendation: 'Redact sensitive fields before logging.',
    confidence_score: 71,
    confidence_reason: 'Found in last 10 logs.',
    created_at: '2026-04-23T08:00:00Z',
    updated_at: '2026-04-23T08:00:00Z',
  },
];

export const mockMeetingSettings = {
  id: 19,
  project_id: 12,
  meeting_days: ['monday', 'thursday'],
  meeting_time: '09:30:00',
  timezone: 'America/Los_Angeles',
  google_meet_link: 'https://meet.google.com/abc-defg-hij',
  weekly_goals: 'Finalize security checklist and merge task updates.',
  monthly_goals: 'Close high severity findings and review onboarding.',
  alert_minutes_before: 30,
  is_active: true,
  last_reminder_sent_at: '2026-04-22T08:00:00Z',
  created_at: '2026-04-10T08:00:00Z',
  updated_at: '2026-04-22T08:00:00Z',
};

export const mockBranches = {
  default_branch: 'main',
  branches: [
    { name: 'main', commit_sha: '7a1d9f', is_default: true },
    { name: 'feature/hardening', commit_sha: '08ce12', is_default: false },
  ],
};

export const mockSeniorSessions = [
  {
    id: 2,
    project_id: 12,
    project_name: 'khaki-labs/guardrail',
    user_id: 7,
    commit_sha: '7a1d9f',
    branch_name: 'main',
    status: 'open',
    created_at: '2026-04-24T08:00:00Z',
    updated_at: '2026-04-24T08:00:00Z',
  },
];

export const mockSeniorMessages = [
  {
    id: 101,
    session_id: 2,
    source_user_message_id: null,
    role: 'assistant',
    input_type: 'text',
    text_content:
      'Good day. How are you today, and may I know your progress and what you have completed so far?',
    structured_payload: {
      check_in_question:
        'Good day. How are you today, and may I know your progress and what you have completed so far?',
      choices: ['Progress update', 'Blocker report', 'Request a review'],
      allow_free_text: true,
    },
    created_at: '2026-04-24T08:00:00Z',
  },
];

export const mockBoards = [
  {
    id: 1,
    name: 'Pinecone Product Development',
    description: 'Main board for Pinecone UI and Agent integration.',
    created_at: '2026-04-01T10:00:00Z',
  },
];

export const mockColumns = [
  { id: 1, board: 1, name: 'To Do', position: 1 },
  { id: 2, board: 1, name: 'In Progress', position: 2 },
  { id: 3, board: 1, name: 'Done', position: 3 },
];

export const mockCards = [
  {
    id: 1,
    column: 1,
    title: 'Implement Auth Guard',
    description: 'Add JWT verification to all sensitive endpoints.',
    position: 1,
    due_date: '2026-05-10T17:00:00Z',
    priority: 'high',
    created_at: '2026-04-05T09:00:00Z',
    updated_at: '2026-04-05T09:00:00Z',
    is_overdue: false,
    labels: [{ id: 1, name: 'Security', color: '#d73a4a' }],
  },
  {
    id: 2,
    column: 2,
    title: 'UI Refactor: Dashboard',
    description: 'Clean up the main dashboard layout and add micro-animations.',
    position: 1,
    due_date: '2026-05-12T12:00:00Z',
    priority: 'medium',
    created_at: '2026-04-06T11:00:00Z',
    updated_at: '2026-04-20T14:00:00Z',
    is_overdue: false,
    labels: [{ id: 2, name: 'Frontend', color: '#0075ca' }],
  },
];

export const mockLabels = [
  { id: 1, board: 1, name: 'Security', color: '#d73a4a' },
  { id: 2, board: 1, name: 'Frontend', color: '#0075ca' },
  { id: 3, board: 1, name: 'Bug', color: '#cfd3d7' },
];

export const mockComments = [
  {
    id: 1,
    card: 1,
    body: 'Started working on the middleware. Checking for edge cases.',
    created_at: '2026-04-10T09:30:00Z',
  },
];
