# Generated by Django 4.2.30 on 2026-05-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('vulnerability_fix', 'Vulnerability fix'), ('feature', 'Feature'), ('bug', 'Bug'), ('refactor', 'Refactor'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=32)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=32)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='todo', max_length=32)),
                ('created_by_agent', models.CharField(blank=True, max_length=255)),
                ('reasoning', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='projects.projectmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('related_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectvulnerability')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMeetingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_days', models.JSONField(blank=True, default=list)),
                ('meeting_time', models.TimeField()),
                ('timezone', models.CharField(max_length=100)),
                ('google_meet_link', models.URLField(max_length=500)),
                ('weekly_goals', models.TextField(blank=True)),
                ('monthly_goals', models.TextField(blank=True)),
                ('alert_minutes_before', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_settings', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
