# Generated by Django 4.2.30 on 2026-05-04 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_projecttask_projectmeetingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_agent', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('task_created', 'Task created'), ('task_assigned', 'Task assigned'), ('task_reassigned', 'Task reassigned'), ('task_updated', 'Task updated'), ('task_priority_changed', 'Task priority changed'), ('task_status_changed', 'Task status changed'), ('task_due_date_changed', 'Task due date changed'), ('task_deleted', 'Task deleted'), ('vulnerability_resolved', 'Vulnerability resolved')], max_length=64)),
                ('target_type', models.CharField(choices=[('project_task', 'Project task'), ('project_vulnerability', 'Project vulnerability')], max_length=64)),
                ('target_id', models.PositiveBigIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
