# Generated by Django 4.2.30 on 2026-05-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_vulnerability_confidence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMeetingSettings',
        ),
    ]
