# Generated by Django 4.2.30 on 2026-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_delete_projectmeetingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectauditlog',
            name='event_type',
            field=models.CharField(choices=[('task_created', 'Task created'), ('task_assigned', 'Task assigned'), ('task_reassigned', 'Task reassigned'), ('task_updated', 'Task updated'), ('task_priority_changed', 'Task priority changed'), ('task_status_changed', 'Task status changed'), ('task_due_date_changed', 'Task due date changed'), ('task_deleted', 'Task deleted'), ('vulnerability_created', 'Vulnerability created'), ('vulnerability_resolved', 'Vulnerability resolved'), ('vulnerability_deleted', 'Vulnerability deleted')], max_length=64),
        ),
    ]
