GITHUB_API_VERSION = '2022-11-28'
GITHUB_AUTHORIZE_URL = 'https://github.com/login/oauth/authorize'
GITHUB_EMAILS_URL = 'https://api.github.com/user/emails'
GITHUB_SCOPE = 'read:user user:email'
GITHUB_TOKEN_URL = 'https://github.com/login/oauth/access_token'
GITHUB_USER_URL = 'https://api.github.com/user'
