# Generated by Django 4.2.30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_role', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('qa', 'QA'), ('security', 'Security'), ('ai_data', 'AI/Data'), ('product_pm', 'Product/PM'), ('design', 'Design'), ('non_technical', 'Non-technical'), ('other', 'Other')], default='other', max_length=32)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('non_technical', 'Non-technical')], default='beginner', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('preferred_tasks', models.JSONField(blank=True, default=list)),
                ('avoided_tasks', models.JSONField(blank=True, default=list)),
                ('availability_notes', models.TextField(blank=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
